name: clang-format Check

env:
  INCLUDE_REGEX: ^.*\.((((c|C)(c|pp|xx|\+\+)?$)|((h|H)h?(pp|xx|\+\+)?$))|(inl|ino|pde|proto|cu))$

on:
  push:
    paths:
      - '**.ino'
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - '**.c'
      - '**.inl'
      - '**clang-format-check.yml'
    pull_request:
      - '**.ino'
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - '**.c'
      - '**.inl'
      - '**clang-format-check.yml'

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          #- check: './'    # path to include
          #  exclude: ''    # path to exclude
          - check: 'src'
          - check: 'test'
          - check: 'examples'
          #   exclude: '(Fonts)' # Exclude file paths containing "Fonts"

    steps:
      - name: Checkout # When pull_request is used, include it in the checkout https://zenn.dev/hkusu/articles/c731862051438b
        uses: actions/checkout@v3.1.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.10.2 # Using include-regex 10.x or later
        with:
          clang-format-version: '13'
          check-path: ${{ matrix.path['check'] }}
          exclude-regex: ${{ matrix.path['exclude'] }}
          include-regex: ${{ env.INCLUDE_REGEX }}
